### ISSUE TITLE
Failure in Gnome 3 "Wayland" environment

### ISSUE THREAD

**Issue by jcewinggh** [dmolony/Xmit#2]
Current Fedora 29 Linux with Gnome 3 defaults to choice of "Wayland" Gnome desktop.  Running Xmit app in that environment fails with "gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed", which indicates a dependency on X11.   If a user explicitly selects at logon in Fedora  the "Gnome Classic" desktop (X-friendly), then it runs successfully.   I have no idea what is needed to support both desktop environments, or if that is even feasible, or how many on Fedora are currently using Wayland; but since Fedora Development seems to be pushing Wayland, that may become more of an issue down the road.  
There are other apps which I  find useful that also don't run under Wayland, so Xmit does have company -- I just found that when I recently migrated to Fedora 29 that my non-Wayland desktop options became broken, and it took a desire to try out your app to force me to get it working.  
It would at least be appropriate to note somewhere in the requirements that Xmit doesn't currently run under a Gnome 3 "Wayland" desktop.

**Comment by dmolony** [comment]
Presumably this is a JVM issue, and at some stage they will fix it. Thanks for spotting the problem.

**Comment by jcewinggh** [comment]
Given that you don't know of any issues in your code, I did a search on OpenJDK and Wayland.  That finds https://github.com/javafxports/openjdk-jfx/issues/175.  Apparently "JavaFX only supports X11", and there aren compatibility issues with openJFX and the X support provided in xwayland on the "Gnome" 3 desktop. Perhaps when that is resolved, xmit will also work with Wayland.

**Comment by mbezzi** [comment]
I experienced the same issue running XmitApp on Ubuntu 18.04. which I *believe* switched back from Wayland to X11. Googling around it seems that this is related to using GTK3 (see https://github.com/javafxports/openjdk-jfx/issues/175). The proposed solution of forcing java to use GTK2 by passing the following runtime option '-Djdk.gtk.version=2' works for me.

/path/to/jdk-11.0.1.jdk/Contents/Home/bin/java \\
--module-path /path/to/javafx-sdk-11/lib \\
--add-modules=javafx.controls \\
-Djdk.gtk.version=2 \\
-Dfile.encoding=UTF-8 \\
-jar /path/to/XmitApp.jar
 
Hope this helps,
mario

**Comment by jcewinggh** [comment]
Adding "-Djdk.gtk.version=2" to the invocation works as a circumvention on Fedora 29 when using the the default Wayland/xwayland desktop  as well, so bug does appear to be some issue with GTK3.

**Comment by dmolony** [comment]
Thanks to both of you for solving this issue.
