### ISSUE TITLE
Usage of "Extract..." function

### ISSUE THREAD

**Issue by jcewinggh** [dmolony/Xmit#3]
I assume the intent of the Files-> Extract <membername>  menu option is to extract the currently selected PDS member and store it somewhere.  Under Fedora 29 when selecting the Extract option I get a "extract binary file" message written to the terminal  window from which xmitapp is executing, but there was no opportunity to specify either a directory or a file name for the extracted data, and so far I have been unable to find any result file either under my current working directory, under the directory containing the viewed XMI file, or even anywhere under my home directory.  I'vee also looked but so far have found no errors logged.  I'm a java neophyte, so this could be something basic, but if I'm missing some step, it's not obvious to me what.

**Comment by dmolony** [comment]
The message you saw should have included the text '(not written yet)'. The only way it works in your version is if the member is an xmit file itself, in which case you will get a save file dialog.
It should work for all member types in the next release.
