### ISSUE TITLE
Xmit run issue

### ISSUE THREAD

**Issue by ddebevec** [dmolony/Xmit#4]
I'm trying to get Xmit to work, but I've ran into a few problems.  I'm currently running:Ubuntu 20.04.1 LTS
openjdk-14-jdk                  - OpenJDK Development Kit (JDK)
openjdk-14-jre                  - OpenJDK Java runtime, using Hotspot JIT
openjdk-14-jdk-headless         - OpenJDK Development Kit (JDK) (headless)
openjdk-14-jre-headless         - OpenJDK Java runtime, using Hotspot JIT (headless)
openjfx-14.0.2.1_linux-x64_bin-sdk
openjfx-14.0.2.1_linux-x64_bin-jmods
I followed the instructions, see the following, but encountered a problem when I tried to execute the program. 
This is the script that I'm trying to run.

/usr/bin/java                \
--module-path /usr/lib/jvm/javafx-sdk-14.0.2.1/lib  \
--add-modules=javafx.controls                     \
--list-modules  \
-Dfile.encoding=UTF-8                             \
-jar /home/ddebevec/XmitApp/XmitApp.jar

I receive the following output:
ddebevec@elisha:~/XmitApp$ ./XmitApp
java.base@14.0.1
java.compiler@14.0.1
java.datatransfer@14.0.1
java.desktop@14.0.1
java.instrument@14.0.1
java.logging@14.0.1
java.management@14.0.1
java.management.rmi@14.0.1
java.naming@14.0.1
java.net.http@14.0.1
java.prefs@14.0.1
java.rmi@14.0.1
java.scripting@14.0.1
java.se@14.0.1
java.security.jgss@14.0.1
java.security.sasl@14.0.1
java.smartcardio@14.0.1
java.sql@14.0.1
java.sql.rowset@14.0.1
java.transaction.xa@14.0.1
java.xml@14.0.1
java.xml.crypto@14.0.1
jdk.accessibility@14.0.1
jdk.aot@14.0.1
jdk.attach@14.0.1
jdk.charsets@14.0.1
jdk.compiler@14.0.1
jdk.crypto.cryptoki@14.0.1
jdk.crypto.ec@14.0.1
jdk.dynalink@14.0.1
jdk.editpad@14.0.1
jdk.hotspot.agent@14.0.1
jdk.httpserver@14.0.1
jdk.incubator.foreign@14.0.1
jdk.incubator.jpackage@14.0.1
jdk.internal.ed@14.0.1
jdk.internal.jvmstat@14.0.1
jdk.internal.le@14.0.1
jdk.internal.opt@14.0.1
jdk.internal.vm.ci@14.0.1
jdk.internal.vm.compiler@14.0.1
jdk.internal.vm.compiler.management@14.0.1
jdk.jartool@14.0.1
jdk.javadoc@14.0.1
jdk.jcmd@14.0.1
jdk.jconsole@14.0.1
jdk.jdeps@14.0.1
jdk.jdi@14.0.1
jdk.jdwp.agent@14.0.1
jdk.jfr@14.0.1
jdk.jlink@14.0.1
jdk.jshell@14.0.1
jdk.jsobject@14.0.1
jdk.jstatd@14.0.1
jdk.localedata@14.0.1
jdk.management@14.0.1
jdk.management.agent@14.0.1
jdk.management.jfr@14.0.1
jdk.naming.dns@14.0.1
jdk.naming.rmi@14.0.1
jdk.net@14.0.1
jdk.nio.mapmode@14.0.1
jdk.rmic@14.0.1
jdk.scripting.nashorn@14.0.1
jdk.scripting.nashorn.shell@14.0.1
jdk.sctp@14.0.1
jdk.security.auth@14.0.1
jdk.security.jgss@14.0.1
jdk.unsupported@14.0.1
jdk.unsupported.desktop@14.0.1
jdk.xml.dom@14.0.1
jdk.zipfs@14.0.1
javafx.base file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.base.jar
javafx.controls file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.controls.jar
javafx.fxml file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.fxml.jar
javafx.graphics file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.graphics.jar
javafx.media file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.media.jar
javafx.swing file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.swing.jar
javafx.swt file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx-swt.jar automatic
javafx.web file:///usr/lib/jvm/javafx-sdk-14.0.2.1/lib/javafx.web.jar

Can you tell me where I'm going wrong?

Thanks!

**Comment by dmolony** [comment]
Hi

I’m not sure which java is executing on your machine, but the output mentions headless which I guess is a server version. You will need a GUI version to run xmit.

Hope this helps.
